apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: litmus-eventrouter
  name: litmus-eventrouter
  namespace: litmus
spec:
  replicas: 1
  selector:
    matchLabels:
      app: litmus-eventrouter
  template:
    metadata:
      labels:
        app: litmus-eventrouter
    spec:
      containers:
      - image: gcr.io/heptio-images/eventrouter:latest
        imagePullPolicy: IfNotPresent
        name: litmus-eventrouter
        env:
          - name: AWS_CLOUDWATCH_METRIC_NAMESPACE
            value: #Namespace in CloudWatch
          - name: CLUSTER_NAME
            value: #Name of a Kubernetes cluster to collect metrics from 
          - name: AWS_ACCESS_KEY_ID
            value: #Valid access key for you AWS account
          - name: AWS_SECRET_ACCESS_KEY
            value: #Valid secret key for you AWS account
          - name: AWS_REGION
            value: #Region where you want to store CloudWatch metrics
        volumeMounts:
        - mountPath: /etc/eventrouter
          name: config-volume
      serviceAccount: litmus
      serviceAccountName: litmus
      volumes:
      - configMap:
          defaultMode: 420
          name: litmus-eventrouter-http-cm
        name: config-volume
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: litmus-eventrouter
  name: litmus-eventrouter
  namespace: litmus
spec:
  ports:
  - nodePort: 31399
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: litmus-eventrouter
  sessionAffinity: None
  type: NodePort

